<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [10]:
import numpy as np
import pandas as pd

### Exercise 1

| Term | Brief description |
| :----|------------------:|
| Subsetting | Categrising a group of elements then further splitting them into subsets, *means to select*|
| Indexing | it is about finding the element using the position of th element in the list or array, *it refers to selecting one element*
|  Slicing | *it refers to selecting a range of elements*| 
|  Masking | *The True/False answer acts like a mask allowing only the True subset to be seen.*|

### Exercise 2

In [12]:
import numpy as np

In [2]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [3]:
first_col = np_array_2d[:, 0]
first_col_int = first_col.astype(int)
remainders = first_col_int % 2


In [4]:
np_array_2d[0:10,0 ]


array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [11]:
first_column_int = np_array_2d[:,0].astype(int)

In [13]:
remainder = first_column_int % 2
remainder

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [14]:
mask = first_column_int % 2 == 1
mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [15]:
np_array_2d[mask]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

### Exercise 3

In [8]:
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

In [9]:
array = np_array = np.array(
   [[66, 50, 57, -1, -1],
    [92, -1, 88, -1, -1],
    [75, -1, -1, 76, -1],
    [-1, 51, 87, -1, -1],
    [71, -1, 67, -1, 69]])

mask_1 = array < 50
mask_2 = array == 50
mask_3 = array > 50

array[mask_1] = -1   
array[mask_2] = 0  
array[mask_3] = 1  

array

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])